---
- name: Running my first play book
  hosts: webservers
  become: yes
  remote_user: ansadmin
  tasks:
     - name: Checking httpd service
       yum:
          name: "httpd"
          state: present
     - name: Uploading Custom index.html
       copy:
           src: /home/ansadmin/index.html
           dest: /var/www/html/index.html
       notify: restart_httpd
     - name: debugging
       debug:
          msg: "hello there is Robot,this can be install in {{ cloud_platform }} or {{ alternative }}"
  handlers: 
    - name: restart_httpd
      service: 
         name: 'httpd'
         state: restarted

